# 언어
language: node_js

# node.js version 14.15.5
node_js:
  - node

# 패키지를 다운 받기 전 install 전에 일어나는 명령
before_install:
  - npm install -g yarn

# 브랜치 설정
branches:
  only:
    - main
    - develop

jobs:
  include:
    - stage: test
      script:
        - cd client
        - yarn install
        - CI=false yarn run test
